gw
cf1
diff_hicp
u_gap
gpty

In [4]:
library(dplyr)
library(readr)
library(restriktor)
library(car)

In [1]:
setwd("/Users/smirovaclav/Documents/blanchard_papery/czechia_data/master_thesis/")

In [5]:
df1 <- read_csv("data_processing/final_dataset/intermediate_data_per_employee_cze.csv", show_col_types = FALSE)
df2 <- read_csv("data_processing/final_dataset/intermediate_data_per_hour_cze.csv", show_col_types = FALSE)

In [6]:
lag_model <- df1 %>%
  mutate(
      
    d_2020Q2 = ifelse(date == "2020Q2", 1, 0),
    d_2021Q1 = ifelse(date == "2021Q1", 1, 0),
    
    gw_lag1 = lag(gw, 1),
    gw_lag2 = lag(gw, 2),
    gw_lag3 = lag(gw, 3),
    gw_lag4 = lag(gw, 4),

    cf1_lag1 = lag(cf1, 1),
    cf1_lag2 = lag(cf1, 2),
    cf1_lag3 = lag(cf1, 3),
    cf1_lag4 = lag(cf1, 4),

    diff_hicp_lag1 = lag(diff_hicp, 1),
    diff_hicp_lag2 = lag(diff_hicp, 2),
    diff_hicp_lag3 = lag(diff_hicp, 3),
    diff_hicp_lag4 = lag(diff_hicp, 4),

    u_gap_lag1 = lag(u_gap, 1),
    u_gap_lag2 = lag(u_gap, 2),
    u_gap_lag3 = lag(u_gap, 3),
    u_gap_lag4 = lag(u_gap, 4),

    gpty_lag1 = lag(gpty, 1)
  ) %>%

  select(
    date, 
    gw,          
    gw_lag1, gw_lag2, gw_lag3, gw_lag4,
    cf1_lag1, cf1_lag2, cf1_lag3, cf1_lag4,
    diff_hicp_lag1, diff_hicp_lag2, diff_hicp_lag3, diff_hicp_lag4,
    u_gap_lag1, u_gap_lag2, u_gap_lag3, u_gap_lag4,
    gpty_lag1,
    d_2020Q2, d_2021Q1
  ) %>%

  na.omit()

wage_model1 <- lm(gw ~ gw_lag1 + gw_lag2 + gw_lag3 + gw_lag4 + 
                      cf1_lag1 + cf1_lag2 + cf1_lag3 + cf1_lag4 +
                      diff_hicp_lag1 + diff_hicp_lag2 + diff_hicp_lag3 + diff_hicp_lag4 +
                      u_gap_lag1 + u_gap_lag2 + u_gap_lag3 + u_gap_lag4 +
                      gpty_lag1 +
                      d_2020Q2 + d_2021Q1,
                      data = lag_model)

summary(wage_model1)

Call:
lm(formula = gw ~ gw_lag1 + gw_lag2 + gw_lag3 + gw_lag4 + cf1_lag1 +
    cf1_lag2 + cf1_lag3 + cf1_lag4 + diff_hicp_lag1 + diff_hicp_lag2 +
    diff_hicp_lag3 + diff_hicp_lag4 + u_gap_lag1 + u_gap_lag2 +
    u_gap_lag3 + u_gap_lag4 + gpty_lag1 + d_2020Q2 + d_2021Q1,
    data = lag_model)

Residuals:
    Min      1Q  Median      3Q     Max
-9.1787 -1.6125  0.2347  1.7458  9.6951

Coefficients:
                 Estimate Std. Error t value Pr(>|t|)
(Intercept)      2.681977   1.396556   1.920  0.05856 .
gw_lag1         -0.245841   0.093469  -2.630  0.01033 *
gw_lag2          0.004878   0.092689   0.053  0.95817
gw_lag3          0.215493   0.104837   2.056  0.04326 *
gw_lag4          0.031639   0.091953   0.344  0.73174
cf1_lag1         0.460771   1.401280   0.329  0.74320
cf1_lag2         2.346024   2.300008   1.020  0.31096
cf1_lag3        -0.162620   2.257633  -0.072  0.94277
cf1_lag4        -2.296725   1.673260  -1.373  0.17391
diff_hicp_lag1  -0.558801   0.646866  -0.864  0.39038
diff_hicp_lag2  -0.913779   0.709935  -1.287  0.20195
diff_hicp_lag3   0.489494   0.708804   0.691  0.49193
diff_hicp_lag4   0.161446   0.493787   0.327  0.74460
u_gap_lag1      -0.508434   1.639265  -0.310  0.75729
u_gap_lag2       0.920097   2.737747   0.336  0.73774
u_gap_lag3       2.677025   2.695621   0.993  0.32381
u_gap_lag4      -3.841972   1.573553  -2.442  0.01695 *
gpty_lag1        0.554658   0.203702   2.723  0.00802 **
d_2020Q2       -27.965582   4.224469  -6.620 4.53e-09 ***
d_2021Q1       -13.165049   5.299929  -2.484  0.01519 *
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 3.972 on 76 degrees of freedom
Multiple R-squared:  0.5977,	Adjusted R-squared:  0.4971
F-statistic: 5.943 on 19 and 76 DF,  p-value: 8.33e-09

In [7]:
# p-stat (sum)
linearHypothesis(wage_model1, "gw_lag1 + gw_lag2 + gw_lag3 + gw_lag4 = 0")
# p-stat (joint)
linearHypothesis(wage_model1, c("gw_lag1=0", "gw_lag2=0", "gw_lag3=0", "gw_lag4=0"))

  Res.Df RSS      Df Sum of Sq  F            Pr(>F)
1 77     1198.998 NA         NA           NA        NA
2 76     1198.985  1 0.01275578 0.0008085495 0.9773897

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 80     1396.429 NA       NA        NA         NA
2 76     1198.985  4 197.4435  3.128834 0.01943339

In [8]:
# p-stat (sum)
linearHypothesis(wage_model1, "cf1_lag1 + cf1_lag2 + cf1_lag3 + cf1_lag4 = 0")
# p-stat (joint)
linearHypothesis(wage_model1, c("cf1_lag1=0", "cf1_lag2=0", "cf1_lag3=0", "cf1_lag4=0"))

  Res.Df RSS      Df Sum of Sq F         Pr(>F)
1 77     1209.106 NA       NA         NA        NA
2 76     1198.985  1 10.12099  0.6415385 0.4256512

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 80     1270.836 NA       NA        NA        NA
2 76     1198.985  4 71.85006  1.138589 0.3448481

In [9]:
# p-stat (sum)
linearHypothesis(wage_model1, "diff_hicp_lag1 + diff_hicp_lag2 + diff_hicp_lag3 + diff_hicp_lag4= 0")
# p-stat (joint)
linearHypothesis(wage_model1, c("diff_hicp_lag1=0", "diff_hicp_lag2=0", "diff_hicp_lag3=0",  "diff_hicp_lag4=0"))

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 77     1258.929 NA       NA        NA         NA
2 76     1198.985  1 59.94377  3.799651 0.05495314

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 80     1291.647 NA      NA         NA        NA
2 76     1198.985  4 92.6611   1.468375 0.2201506

In [10]:
# p-stat (sum)
linearHypothesis(wage_model1, "u_gap_lag1 + u_gap_lag2 + u_gap_lag3 + u_gap_lag4 = 0")
# p-stat (joint)
linearHypothesis(wage_model1, c("u_gap_lag1=0", "u_gap_lag2=0", "u_gap_lag3=0", "u_gap_lag4=0"))

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 77     1298.489 NA       NA        NA         NA
2 76     1198.985  1 99.50357  6.307225 0.01414724

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 80     1422.950 NA      NA         NA         NA
2 76     1198.985  4 223.964   3.549098 0.01041465

In [11]:
# vertical Phillips curve in LR
my_constraints <- 'gw_lag1 + gw_lag2 + gw_lag3 + gw_lag4 + cf1_lag1 + cf1_lag2 + cf1_lag3 + cf1_lag4 = 1'
wage_model_restricted1 <- restriktor(wage_model1, 
                                    constraints = my_constraints)

summary(wage_model_restricted1)

Call:
conLM.lm(object = object, constraints = constraints)

Restriktor: restricted linear model:

Residuals:
     Min       1Q   Median       3Q      Max
-8.95274 -2.13157  0.02244  2.08426 10.62620

Coefficients:
                  Estimate  Std. Error t value  Pr(>|t|)
(Intercept)      0.6653772   0.6556712  1.0148   0.31342
gw_lag1         -0.2465441   0.0944694 -2.6098   0.01091 *
gw_lag2          0.0060946   0.0936791  0.0651   0.94830
gw_lag3          0.2351634   0.1052559  2.2342   0.02841 *
gw_lag4          0.0444347   0.0925993  0.4799   0.63271
cf1_lag1         1.1434221   1.3516058  0.8460   0.40022
cf1_lag2         2.3800607   2.3245543  1.0239   0.30914
cf1_lag3        -0.1370338   2.2817663 -0.0601   0.95227
cf1_lag4        -2.4255977   1.6892996 -1.4359   0.15515
diff_hicp_lag1  -0.8614332   0.6263072 -1.3754   0.17304
diff_hicp_lag2  -0.9231025   0.7175175 -1.2865   0.20217
diff_hicp_lag3   0.5805353   0.7141721  0.8129   0.41883
diff_hicp_lag4  -0.0248784   0.4855297 -0.0512   0.95927
u_gap_lag1      -0.5317627   1.6567652 -0.3210   0.74912
u_gap_lag2       0.7142528   2.7641355  0.2584   0.79680
u_gap_lag3       2.7836864   2.7236989  1.0220   0.31001
u_gap_lag4      -3.7594586   1.5895892 -2.3651   0.02058 *
gpty_lag1        0.5178364   0.2046159  2.5308   0.01345 *
d_2020Q2       -26.7993189   4.2080863 -6.3685 1.324e-08 ***
d_2021Q1       -11.8382119   5.2931989 -2.2365   0.02825 *
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 4.0145 on 76 degrees of freedom
Standard errors: standard
Multiple R-squared remains 0.598

Generalized order-restricted information criterion:
 Loglik Penalty   goric
-259.06   20.00  558.13

In [12]:
beta <- coef(wage_model_restricted1)
sum_gw <- sum(beta[grep("gw_lag", names(beta))])
sum_gw
sum_cf1 <- sum(beta[grep("cf1_lag", names(beta))])
sum_cf1 
sum_u_gap <- sum(beta[grep("u_gap_lag", names(beta))])
sum_u_gap
sum_catchup <- sum(beta[grep("diff_hicp_lag", names(beta))])
sum_catchup
sum_gpty <- sum(beta[grep("gpty_lag1", names(beta))])
sum_gpty

[1] 0.03914867

[1] 0.9608513

[1] -0.7932821

[1] -1.228879

[1] 0.5178364

In [13]:
lag_model <- df2 %>%
  mutate(

    d_2020Q2 = ifelse(date == "2020Q2", 1, 0),
    d_2021Q1 = ifelse(date == "2021Q1", 1, 0),
    
    gw_lag1 = lag(gw, 1),
    gw_lag2 = lag(gw, 2),
    gw_lag3 = lag(gw, 3),
    gw_lag4 = lag(gw, 4),

    cf1_lag1 = lag(cf1, 1),
    cf1_lag2 = lag(cf1, 2),
    cf1_lag3 = lag(cf1, 3),
    cf1_lag4 = lag(cf1, 4),

    diff_hicp_lag1 = lag(diff_hicp, 1),
    diff_hicp_lag2 = lag(diff_hicp, 2),
    diff_hicp_lag3 = lag(diff_hicp, 3),
    diff_hicp_lag4 = lag(diff_hicp, 4),

    u_gap_lag1 = lag(u_gap, 1),
    u_gap_lag2 = lag(u_gap, 2),
    u_gap_lag3 = lag(u_gap, 3),
    u_gap_lag4 = lag(u_gap, 4),

    gpty_lag1 = lag(gpty, 1)
  ) %>%

  select(
    date, 
    gw,          
    gw_lag1, gw_lag2, gw_lag3, gw_lag4,
    cf1_lag1, cf1_lag2, cf1_lag3, cf1_lag4,
    diff_hicp_lag1, diff_hicp_lag2, diff_hicp_lag3, diff_hicp_lag4,
    u_gap_lag1, u_gap_lag2, u_gap_lag3, u_gap_lag4,
    gpty_lag1,
    d_2020Q2, d_2021Q1
  ) %>%

  na.omit()

wage_model2 <- lm(gw ~ gw_lag1 + gw_lag2 + gw_lag3 + gw_lag4 + 
                      cf1_lag1 + cf1_lag2 + cf1_lag3 + cf1_lag4 +
                      diff_hicp_lag1 + diff_hicp_lag2 + diff_hicp_lag3 + diff_hicp_lag4 +
                      u_gap_lag1 + u_gap_lag2 + u_gap_lag3 + u_gap_lag4 +
                      gpty_lag1 +
                      d_2020Q2 + d_2021Q1,
                      data = lag_model)

summary(wage_model2)

Call:
lm(formula = gw ~ gw_lag1 + gw_lag2 + gw_lag3 + gw_lag4 + cf1_lag1 +
    cf1_lag2 + cf1_lag3 + cf1_lag4 + diff_hicp_lag1 + diff_hicp_lag2 +
    diff_hicp_lag3 + diff_hicp_lag4 + u_gap_lag1 + u_gap_lag2 +
    u_gap_lag3 + u_gap_lag4 + gpty_lag1 + d_2020Q2 + d_2021Q1,
    data = lag_model)

Residuals:
     Min       1Q   Median       3Q      Max
-14.7110  -3.0920   0.0644   3.5155  22.0002

Coefficients:
                Estimate Std. Error t value Pr(>|t|)
(Intercept)      2.22303    2.31528   0.960  0.34002
gw_lag1         -0.55082    0.12845  -4.288 5.23e-05 ***
gw_lag2         -0.06331    0.12458  -0.508  0.61279
gw_lag3          0.37315    0.11597   3.218  0.00190 **
gw_lag4          0.29537    0.10909   2.708  0.00837 **
cf1_lag1        -0.43275    2.21195  -0.196  0.84541
cf1_lag2         4.46463    3.65724   1.221  0.22595
cf1_lag3         0.32288    3.62105   0.089  0.92918
cf1_lag4        -3.86021    2.65682  -1.453  0.15036
diff_hicp_lag1  -0.57748    1.00947  -0.572  0.56897
diff_hicp_lag2  -1.17152    1.13365  -1.033  0.30469
diff_hicp_lag3   0.19924    1.13168   0.176  0.86072
diff_hicp_lag4   0.29536    0.78110   0.378  0.70639
u_gap_lag1      -0.95045    2.54252  -0.374  0.70958
u_gap_lag2      -2.40633    4.35498  -0.553  0.58220
u_gap_lag3       6.77181    4.33363   1.563  0.12230
u_gap_lag4      -4.52160    2.66108  -1.699  0.09338 .
gpty_lag1        0.33374    0.55345   0.603  0.54829
d_2020Q2         3.72982    7.46617   0.500  0.61883
d_2021Q1       -16.60382    7.95397  -2.087  0.04020 *
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 6.328 on 76 degrees of freedom
Multiple R-squared:  0.4362,	Adjusted R-squared:  0.2953
F-statistic: 3.095 on 19 and 76 DF,  p-value: 0.0002486

In [14]:
# p-stat (sum)
linearHypothesis(wage_model2, "gw_lag1 + gw_lag2 + gw_lag3 + gw_lag4 = 0")
# p-stat (joint)
linearHypothesis(wage_model2, c("gw_lag1=0", "gw_lag2=0", "gw_lag3=0", "gw_lag4=0"))

  Res.Df RSS      Df Sum of Sq F          Pr(>F)
1 77     3044.540 NA       NA          NA        NA
2 76     3043.367  1 1.172988  0.02929227 0.8645608

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 80     4387.067 NA       NA        NA           NA
2 76     3043.367  4 1343.701  8.388838 1.165598e-05

In [15]:
# p-stat (sum)
linearHypothesis(wage_model2, "cf1_lag1 + cf1_lag2 + cf1_lag3 + cf1_lag4 = 0")
# p-stat (joint)
linearHypothesis(wage_model2, c("cf1_lag1=0", "cf1_lag2=0", "cf1_lag3=0", "cf1_lag4=0"))

  Res.Df RSS      Df Sum of Sq F         Pr(>F)
1 77     3063.544 NA       NA         NA        NA
2 76     3043.367  1 20.17778  0.5038865 0.4799697

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 80     3214.421 NA       NA        NA        NA
2 76     3043.367  4 171.0547  1.067909 0.3783326

In [16]:
# p-stat (sum)
linearHypothesis(wage_model2, "diff_hicp_lag1 + diff_hicp_lag2 + diff_hicp_lag3 + diff_hicp_lag4= 0")
# p-stat (joint)
linearHypothesis(wage_model2, c("diff_hicp_lag1=0", "diff_hicp_lag2=0", "diff_hicp_lag3=0",  "diff_hicp_lag4=0"))

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 77     3194.622 NA       NA        NA         NA
2 76     3043.367  1 151.2556  3.777207 0.05565782

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 80     3244.214 NA       NA        NA        NA
2 76     3043.367  4 200.8475  1.253909 0.2955815

In [17]:
# p-stat (sum)
linearHypothesis(wage_model2, "u_gap_lag1 + u_gap_lag2 + u_gap_lag3 + u_gap_lag4 = 0")
# p-stat (joint)
linearHypothesis(wage_model2, c("u_gap_lag1=0", "u_gap_lag2=0", "u_gap_lag3=0", "u_gap_lag4=0"))

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 77     3221.600 NA       NA        NA         NA
2 76     3043.367  1 178.2333  4.450903 0.03817477

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 80     3311.320 NA       NA        NA        NA
2 76     3043.367  4 267.9532  1.672855 0.1650229

In [18]:
# vertical Phillips curve in LR
my_constraints <- 'gw_lag1 + gw_lag2 + gw_lag3 + gw_lag4 + cf1_lag1 + cf1_lag2 + cf1_lag3 + cf1_lag4 = 1'
wage_model_restricted2 <- restriktor(wage_model2, 
                                    constraints = my_constraints)

summary(wage_model_restricted2)

Call:
conLM.lm(object = object, constraints = constraints)

Restriktor: restricted linear model:

Residuals:
      Min        1Q    Median        3Q       Max
-14.42803  -3.12122   0.25163   3.55793  22.46741

Coefficients:
                 Estimate Std. Error t value  Pr(>|t|)
(Intercept)      0.728087   0.977914  0.7445  0.458852
gw_lag1         -0.551945   0.128031 -4.3110 4.816e-05 ***
gw_lag2         -0.057241   0.123888 -0.4620  0.645371
gw_lag3          0.377678   0.115428  3.2720  0.001608 **
gw_lag4          0.294915   0.108737  2.7122  0.008262 **
cf1_lag1         0.050861   2.098604  0.0242  0.980728
cf1_lag2         4.427799   3.645180  1.2147  0.228241
cf1_lag3         0.409272   3.607443  0.1135  0.909971
cf1_lag4        -3.951337   2.645258 -1.4937  0.139383
diff_hicp_lag1  -0.777899   0.966424 -0.8049  0.423374
diff_hicp_lag2  -1.185880   1.129844 -1.0496  0.297230
diff_hicp_lag3   0.259776   1.124882  0.2309  0.817985
diff_hicp_lag4   0.173491   0.759721  0.2284  0.819978
u_gap_lag1      -0.964229   2.534314 -0.3805  0.704658
u_gap_lag2      -2.480330   4.339810 -0.5715  0.569327
u_gap_lag3       6.846938   4.318487  1.5855  0.117006
u_gap_lag4      -4.540653   2.652432 -1.7119  0.090996 .
gpty_lag1        0.358175   0.550624  0.6505  0.517339
d_2020Q2         4.401348   7.382810  0.5962  0.552839
d_2021Q1       -16.033316   7.888286 -2.0325  0.045592 *
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 6.3078 on 76 degrees of freedom
Standard errors: standard
Multiple R-squared remains 0.436

Generalized order-restricted information criterion:
 Loglik Penalty   goric
-302.44   20.00  644.89

In [19]:
beta <- coef(wage_model_restricted2)
sum_gw <- sum(beta[grep("gw_lag", names(beta))])
sum_gw
sum_cf1 <- sum(beta[grep("cf1_lag", names(beta))])
sum_cf1 
sum_u_gap <- sum(beta[grep("u_gap_lag", names(beta))])
sum_u_gap
sum_catchup <- sum(beta[grep("diff_hicp_lag", names(beta))])
sum_catchup
sum_gpty <- sum(beta[grep("gpty_lag1", names(beta))])
sum_gpty

[1] 0.06340654

[1] 0.9365935

[1] -1.138274

[1] -1.530511

[1] 0.3581746