gw
cf1
diff_hicp
u_gap
gpty

In [2]:
library(dplyr)
library(readr)
library(restriktor)
library(car)

In [5]:
setwd("/Users/smirovaclav/Documents/blanchard_papery/czechia_data/master_thesis")

In [6]:
df1 <- read_csv("data_processing/final_dataset/intermediate_data_per_employee_cze.csv", show_col_types = FALSE)
df2 <- read_csv("data_processing/final_dataset/intermediate_data_per_hour_cze.csv", show_col_types = FALSE)

In [7]:
lag_model <- df1 %>%
  mutate(
      
    d_2020Q2 = ifelse(date == "2020Q2", 1, 0),
    d_2021Q1 = ifelse(date == "2021Q1", 1, 0),
    
    gw_lag1 = lag(gw, 1),
    gw_lag2 = lag(gw, 2),
    gw_lag3 = lag(gw, 3),
    gw_lag4 = lag(gw, 4),

    cf1_lag1 = lag(cf1, 1),
    cf1_lag2 = lag(cf1, 2),
    cf1_lag3 = lag(cf1, 3),
    cf1_lag4 = lag(cf1, 4),

    diff_cpi_lag1 = lag(diff_cpi, 1),
    diff_cpi_lag2 = lag(diff_cpi, 2),
    diff_cpi_lag3 = lag(diff_cpi, 3),
    diff_cpi_lag4 = lag(diff_cpi, 4),

    u_gap_lag1 = lag(u_gap, 1),
    u_gap_lag2 = lag(u_gap, 2),
    u_gap_lag3 = lag(u_gap, 3),
    u_gap_lag4 = lag(u_gap, 4),

    gpty_lag1 = lag(gpty, 1)
  ) %>%

  select(
    date, 
    gw,          
    gw_lag1, gw_lag2, gw_lag3, gw_lag4,
    cf1_lag1, cf1_lag2, cf1_lag3, cf1_lag4,
    diff_cpi_lag1, diff_cpi_lag2, diff_cpi_lag3, diff_cpi_lag4,
    u_gap_lag1, u_gap_lag2, u_gap_lag3, u_gap_lag4,
    gpty_lag1,
    d_2020Q2, d_2021Q1
  ) %>%

  na.omit()

wage_model1 <- lm(gw ~ gw_lag1 + gw_lag2 + gw_lag3 + gw_lag4 + 
                      cf1_lag1 + cf1_lag2 + cf1_lag3 + cf1_lag4 +
                      diff_cpi_lag1 + diff_cpi_lag2 + diff_cpi_lag3 + diff_cpi_lag4 +
                      u_gap_lag1 + u_gap_lag2 + u_gap_lag3 + u_gap_lag4 +
                      gpty_lag1 +
                      d_2020Q2 + d_2021Q1,
                      data = lag_model)

summary(wage_model1)

Call:
lm(formula = gw ~ gw_lag1 + gw_lag2 + gw_lag3 + gw_lag4 + cf1_lag1 +
    cf1_lag2 + cf1_lag3 + cf1_lag4 + diff_cpi_lag1 + diff_cpi_lag2 +
    diff_cpi_lag3 + diff_cpi_lag4 + u_gap_lag1 + u_gap_lag2 +
    u_gap_lag3 + u_gap_lag4 + gpty_lag1 + d_2020Q2 + d_2021Q1,
    data = lag_model)

Residuals:
   Min     1Q Median     3Q    Max
-9.114 -1.840  0.000  1.784  9.449

Coefficients:
               Estimate Std. Error t value Pr(>|t|)
(Intercept)     2.81757    1.34691   2.092  0.03979 *
gw_lag1        -0.24677    0.09215  -2.678  0.00908 **
gw_lag2         0.01013    0.09051   0.112  0.91119
gw_lag3         0.21686    0.10310   2.103  0.03875 *
gw_lag4         0.03431    0.09073   0.378  0.70635
cf1_lag1        0.83877    1.42139   0.590  0.55687
cf1_lag2        2.64940    2.27390   1.165  0.24761
cf1_lag3       -0.46600    2.25996  -0.206  0.83719
cf1_lag4       -2.71599    1.66308  -1.633  0.10658
diff_cpi_lag1  -0.72217    0.65421  -1.104  0.27313
diff_cpi_lag2  -1.10351    0.70740  -1.560  0.12292
diff_cpi_lag3   0.63236    0.70433   0.898  0.37212
diff_cpi_lag4   0.21213    0.48828   0.434  0.66519
u_gap_lag1     -0.33471    1.60622  -0.208  0.83548
u_gap_lag2      0.76234    2.69027   0.283  0.77766
u_gap_lag3      2.60243    2.64975   0.982  0.32915
u_gap_lag4     -3.80106    1.54693  -2.457  0.01628 *
gpty_lag1       0.56245    0.20042   2.806  0.00636 **
d_2020Q2      -28.07940    4.15355  -6.760 2.47e-09 ***
d_2021Q1      -13.47352    5.21676  -2.583  0.01172 *
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 3.914 on 76 degrees of freedom
Multiple R-squared:  0.6093,	Adjusted R-squared:  0.5117
F-statistic: 6.239 on 19 and 76 DF,  p-value: 3.19e-09

In [8]:
# p-stat (sum)
linearHypothesis(wage_model1, "gw_lag1 + gw_lag2 + gw_lag3 + gw_lag4 = 0")
# p-stat (joint)
linearHypothesis(wage_model1, c("gw_lag1=0", "gw_lag2=0", "gw_lag3=0", "gw_lag4=0"))

  Res.Df RSS      Df Sum of Sq  F           Pr(>F)
1 77     1164.350 NA         NA          NA        NA
2 76     1164.278  1 0.07192148 0.004694783 0.9455529

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 80     1362.473 NA       NA        NA         NA
2 76     1164.278  4 198.1956  3.234379 0.01661311

In [9]:
# p-stat (sum)
linearHypothesis(wage_model1, "cf1_lag1 + cf1_lag2 + cf1_lag3 + cf1_lag4 = 0")
# p-stat (joint)
linearHypothesis(wage_model1, c("cf1_lag1=0", "cf1_lag2=0", "cf1_lag3=0", "cf1_lag4=0"))

  Res.Df RSS      Df Sum of Sq F         Pr(>F)
1 77     1172.802 NA       NA         NA        NA
2 76     1164.278  1 8.524442  0.5564459 0.4579969

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 80     1268.162 NA       NA        NA        NA
2 76     1164.278  4 103.8846  1.695305 0.1598273

In [10]:
# p-stat (sum)
linearHypothesis(wage_model1, "diff_cpi_lag1 + diff_cpi_lag2 + diff_cpi_lag3 + diff_cpi_lag4 = 0")
# p-stat (joint)
linearHypothesis(wage_model1, c("diff_cpi_lag1=0", "diff_cpi_lag2=0", "diff_cpi_lag3=0", "diff_cpi_lag4=0"))

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 77     1243.624 NA       NA        NA         NA
2 76     1164.278  1 79.34634  5.179452 0.02567288

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 80     1291.647 NA       NA        NA         NA
2 76     1164.278  4 127.3687  2.078546 0.09185994

In [11]:
# p-stat (sum)
linearHypothesis(wage_model1, "u_gap_lag1 + u_gap_lag2 + u_gap_lag3 + u_gap_lag4 = 0")
# p-stat (joint)
linearHypothesis(wage_model1, c("u_gap_lag1=0", "u_gap_lag2=0", "u_gap_lag3=0", "u_gap_lag4=0"))

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 77     1272.799 NA       NA        NA          NA
2 76     1164.278  1 108.5208  7.083856 0.009486747

  Res.Df RSS      Df Sum of Sq F       Pr(>F)
1 80     1397.684 NA       NA       NA          NA
2 76     1164.278  4 233.4065  3.80899 0.007090006

In [12]:
# vertical Phillips curve in LR
my_constraints <- 'gw_lag1 + gw_lag2 + gw_lag3 + gw_lag4 + cf1_lag1 + cf1_lag2 + cf1_lag3 + cf1_lag4 = 1'
wage_model_restricted1 <- restriktor(wage_model1, 
                                    constraints = my_constraints)

summary(wage_model_restricted1)

Call:
conLM.lm(object = object, constraints = constraints)

Restriktor: restricted linear model:

Residuals:
     Min       1Q   Median       3Q      Max
-8.38225 -2.26726  0.17121  1.94934 10.42282

Coefficients:
                Estimate Std. Error t value  Pr(>|t|)
(Intercept)     0.699542   0.649994  1.0762   0.28523
gw_lag1        -0.243719   0.093441 -2.6083   0.01095 *
gw_lag2         0.016828   0.091708  0.1835   0.85489
gw_lag3         0.241481   0.103626  2.3303   0.02244 *
gw_lag4         0.049039   0.091639  0.5351   0.59412
cf1_lag1        1.633235   1.369270  1.1928   0.23667
cf1_lag2        2.619001   2.306043  1.1357   0.25965
cf1_lag3       -0.484747   2.291940 -0.2115   0.83306
cf1_lag4       -2.831118   1.685367 -1.6798   0.09710 .
diff_cpi_lag1  -1.034692   0.639359 -1.6183   0.10974
diff_cpi_lag2  -1.106829   0.717415 -1.5428   0.12703
diff_cpi_lag3   0.725614   0.712346  1.0186   0.31161
diff_cpi_lag4   0.013266   0.482175  0.0275   0.97812
u_gap_lag1     -0.252434   1.628301 -0.1550   0.87721
u_gap_lag2      0.474669   2.723494  0.1743   0.86210
u_gap_lag3      2.690764   2.686812  1.0015   0.31978
u_gap_lag4     -3.698432   1.567760 -2.3591   0.02089 *
gpty_lag1       0.526872   0.202251  2.6050   0.01105 *
d_2020Q2      -26.837231   4.153027 -6.4621 8.888e-09 ***
d_2021Q1      -12.147267   5.236889 -2.3196   0.02305 *
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 3.9694 on 76 degrees of freedom
Standard errors: standard
Multiple R-squared remains 0.609

Generalized order-restricted information criterion:
 Loglik Penalty   goric
-257.98   20.00  555.96

In [13]:
beta <- coef(wage_model_restricted1)
sum_gw <- sum(beta[grep("gw_lag", names(beta))])
sum_gw
sum_cf1 <- sum(beta[grep("cf1_lag", names(beta))])
sum_cf1 
sum_u_gap <- sum(beta[grep("u_gap_lag", names(beta))])
sum_u_gap
sum_catchup <- sum(beta[grep("diff_cpi_lag", names(beta))])
sum_catchup
sum_gpty <- sum(beta[grep("gpty_lag1", names(beta))])
sum_gpty

[1] 0.0636292

[1] 0.9363708

[1] -0.785433

[1] -1.402642

[1] 0.5268718

## Compensation per hour

In [21]:
lag_model <- df2 %>%
  mutate(

    d_2020Q2 = ifelse(date == "2020Q2", 1, 0),
    d_2021Q1 = ifelse(date == "2021Q1", 1, 0),
    
    gw_lag1 = lag(gw, 1),
    gw_lag2 = lag(gw, 2),
    gw_lag3 = lag(gw, 3),
    gw_lag4 = lag(gw, 4),

    cf1_lag1 = lag(cf1, 1),
    cf1_lag2 = lag(cf1, 2),
    cf1_lag3 = lag(cf1, 3),
    cf1_lag4 = lag(cf1, 4),

    diff_cpi_lag1 = lag(diff_cpi, 1),
    diff_cpi_lag2 = lag(diff_cpi, 2),
    diff_cpi_lag3 = lag(diff_cpi, 3),
    diff_cpi_lag4 = lag(diff_cpi, 4),

    u_gap_lag1 = lag(u_gap, 1),
    u_gap_lag2 = lag(u_gap, 2),
    u_gap_lag3 = lag(u_gap, 3),
    u_gap_lag4 = lag(u_gap, 4),

    gpty_lag1 = lag(gpty, 1)
  ) %>%

  select(
    date, 
    gw,          
    gw_lag1, gw_lag2, gw_lag3, gw_lag4,
    cf1_lag1, cf1_lag2, cf1_lag3, cf1_lag4,
    diff_cpi_lag1, diff_cpi_lag2, diff_cpi_lag3, diff_cpi_lag4,
    u_gap_lag1, u_gap_lag2, u_gap_lag3, u_gap_lag4,
    gpty_lag1,
    d_2020Q2, d_2021Q1
  ) %>%

  na.omit()

wage_model2 <- lm(gw ~ gw_lag1 + gw_lag2 + gw_lag3 + gw_lag4 + 
                      cf1_lag1 + cf1_lag2 + cf1_lag3 + cf1_lag4 +
                      diff_cpi_lag1 + diff_cpi_lag2 + diff_cpi_lag3 + diff_cpi_lag4 +
                      u_gap_lag1 + u_gap_lag2 + u_gap_lag3 + u_gap_lag4 +
                      gpty_lag1 +
                      d_2020Q2 + d_2021Q1,
                      data = lag_model)

summary(wage_model2)

Call:
lm(formula = gw ~ gw_lag1 + gw_lag2 + gw_lag3 + gw_lag4 + cf1_lag1 +
    cf1_lag2 + cf1_lag3 + cf1_lag4 + diff_cpi_lag1 + diff_cpi_lag2 +
    diff_cpi_lag3 + diff_cpi_lag4 + u_gap_lag1 + u_gap_lag2 +
    u_gap_lag3 + u_gap_lag4 + gpty_lag1 + d_2020Q2 + d_2021Q1,
    data = lag_model)

Residuals:
    Min      1Q  Median      3Q     Max
-15.225  -3.291   0.000   3.336  21.997

Coefficients:
               Estimate Std. Error t value Pr(>|t|)
(Intercept)     2.47528    2.26486   1.093  0.27789
gw_lag1        -0.54550    0.12774  -4.270 5.58e-05 ***
gw_lag2        -0.06629    0.12376  -0.536  0.59375
gw_lag3         0.36517    0.11569   3.156  0.00229 **
gw_lag4         0.29378    0.10903   2.695  0.00867 **
cf1_lag1        0.42932    2.27551   0.189  0.85085
cf1_lag2        4.52603    3.66248   1.236  0.22035
cf1_lag3       -0.58914    3.67507  -0.160  0.87306
cf1_lag4       -3.92341    2.67040  -1.469  0.14590
diff_cpi_lag1  -0.96238    1.03713  -0.928  0.35638
diff_cpi_lag2  -1.22175    1.14683  -1.065  0.29010
diff_cpi_lag3   0.59256    1.13830   0.521  0.60418
diff_cpi_lag4   0.15437    0.78121   0.198  0.84388
u_gap_lag1     -0.78627    2.52755  -0.311  0.75659
u_gap_lag2     -2.58673    4.32846  -0.598  0.55188
u_gap_lag3      6.89728    4.31024   1.600  0.11370
u_gap_lag4     -4.66723    2.65298  -1.759  0.08256 .
gpty_lag1       0.36754    0.55096   0.667  0.50674
d_2020Q2        3.51983    7.41098   0.475  0.63619
d_2021Q1      -17.33503    7.91690  -2.190  0.03162 *
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 6.309 on 76 degrees of freedom
Multiple R-squared:  0.4395,	Adjusted R-squared:  0.2994
F-statistic: 3.137 on 19 and 76 DF,  p-value: 0.0002111

In [22]:
# p-stat (sum)
linearHypothesis(wage_model2, "gw_lag1 + gw_lag2 + gw_lag3 + gw_lag4 = 0")
# p-stat (joint)
linearHypothesis(wage_model2, c("gw_lag1=0", "gw_lag2=0", "gw_lag3=0", "gw_lag4=0"))

  Res.Df RSS      Df Sum of Sq F          Pr(>F)
1 77     3026.412 NA        NA         NA        NA
2 76     3025.523  1 0.8895987 0.02234639 0.8815653

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 80     4330.368 NA       NA        NA           NA
2 76     3025.523  4 1304.846  8.194308 1.505404e-05

In [23]:
# p-stat (sum)
linearHypothesis(wage_model2, "cf1_lag1 + cf1_lag2 + cf1_lag3 + cf1_lag4 = 0")
# p-stat (joint)
linearHypothesis(wage_model2, c("cf1_lag1=0", "cf1_lag2=0", "cf1_lag3=0", "cf1_lag4=0"))

  Res.Df RSS      Df Sum of Sq F         Pr(>F)
1 77     3042.384 NA       NA         NA        NA
2 76     3025.523  1 16.86087  0.4235388 0.5171393

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 80     3235.049 NA       NA        NA        NA
2 76     3025.523  4 209.5259  1.315803 0.2717486

In [24]:
# p-stat (sum)
linearHypothesis(wage_model2, "diff_cpi_lag1 + diff_cpi_lag2 + diff_cpi_lag3 + diff_cpi_lag4 = 0")
# p-stat (joint)
linearHypothesis(wage_model2, c("diff_cpi_lag1=0", "diff_cpi_lag2=0", "diff_cpi_lag3=0", "diff_cpi_lag4=0"))

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 77     3204.379 NA       NA        NA         NA
2 76     3025.523  1 178.8567  4.492815 0.03730258

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 80     3244.214 NA       NA        NA        NA
2 76     3025.523  4 218.6914  1.373362 0.2511283

In [25]:
# p-stat (sum)
linearHypothesis(wage_model2, "u_gap_lag1 + u_gap_lag2 + u_gap_lag3 + u_gap_lag4 = 0")
# p-stat (joint)
linearHypothesis(wage_model2, c("u_gap_lag1=0", "u_gap_lag2=0", "u_gap_lag3=0", "u_gap_lag4=0"))

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 77     3215.196 NA       NA        NA         NA
2 76     3025.523  1 189.6734  4.764525 0.03214038

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 80     3305.252 NA       NA        NA       NA
2 76     3025.523  4 279.7291  1.756673 0.146401

In [26]:
# vertical Phillips curve in LR
my_constraints <- 'gw_lag1 + gw_lag2 + gw_lag3 + gw_lag4 + cf1_lag1 + cf1_lag2 + cf1_lag3 + cf1_lag4 = 1'
wage_model_restricted2 <- restriktor(wage_model2, 
                                    constraints = my_constraints)

summary(wage_model_restricted2)

Call:
conLM.lm(object = object, constraints = constraints)

Restriktor: restricted linear model:

Residuals:
      Min        1Q    Median        3Q       Max
-14.96154  -3.07815   0.34501   3.56717  22.53567

Coefficients:
                Estimate Std. Error t value  Pr(>|t|)
(Intercept)     0.783425   0.974921  0.8036  0.424147
gw_lag1        -0.545387   0.127482 -4.2781 5.426e-05 ***
gw_lag2        -0.059814   0.123261 -0.4853  0.628885
gw_lag3         0.369376   0.115342  3.2024  0.001991 **
gw_lag4         0.293754   0.108806  2.6998  0.008548 **
cf1_lag1        1.045159   2.146128  0.4870  0.627662
cf1_lag2        4.424376   3.652943  1.2112  0.229579
cf1_lag3       -0.513611   3.666426 -0.1401  0.888964
cf1_lag4       -4.013852   2.662710 -1.5074  0.135846
diff_cpi_lag1  -1.189802   0.998060 -1.1921  0.236926
diff_cpi_lag2  -1.227227   1.144467 -1.0723  0.286973
diff_cpi_lag3   0.655924   1.133406  0.5787  0.564490
diff_cpi_lag4   0.011292   0.760298  0.0149  0.988189
u_gap_lag1     -0.733450   2.521579 -0.2909  0.771944
u_gap_lag2     -2.718155   4.316703 -0.6297  0.530790
u_gap_lag3      6.984445   4.300152  1.6242  0.108467
u_gap_lag4     -4.705178   2.647160 -1.7774  0.079496 .
gpty_lag1       0.410577   0.547378  0.7501  0.455523
d_2020Q2        4.210572   7.348821  0.5730  0.568364
d_2021Q1      -16.856432   7.879628 -2.1392  0.035627 *
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 6.2966 on 76 degrees of freedom
Standard errors: standard
Multiple R-squared remains 0.440

Generalized order-restricted information criterion:
 Loglik Penalty   goric
-302.27   20.00  644.55

In [27]:
beta <- coef(wage_model_restricted2)
sum_gw <- sum(beta[grep("gw_lag", names(beta))])
sum_gw
sum_cf1 <- sum(beta[grep("cf1_lag", names(beta))])
sum_cf1 
sum_u_gap <- sum(beta[grep("u_gap_lag", names(beta))])
sum_u_gap
sum_catchup <- sum(beta[grep("diff_cpi_lag", names(beta))])
sum_catchup
sum_gpty <- sum(beta[grep("gpty_lag1", names(beta))])
sum_gpty

[1] 0.05792874

[1] 0.9420713

[1] -1.172338

[1] -1.749813

[1] 0.4105773