gw
cf1
diff_cpi
vu
gpty

In [2]:
library(dplyr)
library(readr)
library(restriktor)
library(car)

In [7]:
getwd()
setwd("/Users/smirovaclav/Documents/blanchard_papery/czechia_data/master_thesis")

[1] "/Users/smirovaclav/Documents/blanchard_papery/czechia_data/master_thesis"

In [8]:
df1 <- read_csv("data_processing/final_dataset/intermediate_data_per_employee_cze.csv", show_col_types = FALSE)
df2 <- read_csv("data_processing/final_dataset/intermediate_data_per_hour_cze.csv", show_col_types = FALSE)

In [9]:
lag_model <- df1 %>%
  mutate(

    d_2020Q2 = ifelse(date == "2020Q2", 1, 0),
    d_2021Q1 = ifelse(date == "2021Q1", 1, 0),
    
    gw_lag1 = lag(gw, 1),
    gw_lag2 = lag(gw, 2),
    gw_lag3 = lag(gw, 3),
    gw_lag4 = lag(gw, 4),

    cf1_lag1 = lag(cf1, 1),
    cf1_lag2 = lag(cf1, 2),
    cf1_lag3 = lag(cf1, 3),
    cf1_lag4 = lag(cf1, 4),

    diff_cpi_lag1 = lag(diff_cpi, 1),
    diff_cpi_lag2 = lag(diff_cpi, 2),
    diff_cpi_lag3 = lag(diff_cpi, 3),
    diff_cpi_lag4 = lag(diff_cpi, 4),

    vu_lag1 = lag(vu, 1),
    vu_lag2 = lag(vu, 2),
    vu_lag3 = lag(vu, 3),
    vu_lag4 = lag(vu, 4),

    gpty_lag1 = lag(gpty, 1)
  ) %>%

  select(
    date, 
    gw,          
    gw_lag1, gw_lag2, gw_lag3, gw_lag4,
    cf1_lag1, cf1_lag2, cf1_lag3, cf1_lag4,
    diff_cpi_lag1, diff_cpi_lag2, diff_cpi_lag3, diff_cpi_lag4,
    vu_lag1, vu_lag2, vu_lag3, vu_lag4,
    gpty_lag1,
    d_2020Q2, d_2021Q1
  ) %>%

  na.omit()

wage_model1 <- lm(gw ~ gw_lag1 + gw_lag2 + gw_lag3 + gw_lag4 + 
                      cf1_lag1 + cf1_lag2 + cf1_lag3 + cf1_lag4 +
                      diff_cpi_lag1 + diff_cpi_lag2 + diff_cpi_lag3 + diff_cpi_lag4 +
                      vu_lag1 + vu_lag2 + vu_lag3 + vu_lag4 +
                      gpty_lag1 +
                      d_2020Q2 + d_2021Q1,
                      data = lag_model)

summary(wage_model1)

Call:
lm(formula = gw ~ gw_lag1 + gw_lag2 + gw_lag3 + gw_lag4 + cf1_lag1 +
    cf1_lag2 + cf1_lag3 + cf1_lag4 + diff_cpi_lag1 + diff_cpi_lag2 +
    diff_cpi_lag3 + diff_cpi_lag4 + vu_lag1 + vu_lag2 + vu_lag3 +
    vu_lag4 + gpty_lag1 + d_2020Q2 + d_2021Q1, data = lag_model)

Residuals:
    Min      1Q  Median      3Q     Max
-8.9963 -1.9422  0.1213  2.1259  7.6974

Coefficients:
               Estimate Std. Error t value Pr(>|t|)
(Intercept)     3.02156    1.38208   2.186  0.03188 *
gw_lag1        -0.16182    0.09918  -1.632  0.10692
gw_lag2         0.18209    0.10479   1.738  0.08631 .
gw_lag3         0.32505    0.10809   3.007  0.00357 **
gw_lag4         0.09573    0.09396   1.019  0.31148
cf1_lag1        0.71556    1.39096   0.514  0.60844
cf1_lag2        2.62266    2.24338   1.169  0.24603
cf1_lag3       -0.13943    2.21558  -0.063  0.94999
cf1_lag4       -3.83995    1.67270  -2.296  0.02445 *
diff_cpi_lag1  -0.60158    0.63107  -0.953  0.34347
diff_cpi_lag2  -1.43323    0.68839  -2.082  0.04071 *
diff_cpi_lag3   0.46965    0.68772   0.683  0.49674
diff_cpi_lag4   0.78759    0.52299   1.506  0.13623
vu_lag1        -7.77719    5.59939  -1.389  0.16891
vu_lag2        -2.73151    8.38475  -0.326  0.74549
vu_lag3        10.07303    9.82081   1.026  0.30829
vu_lag4         3.61977    6.64910   0.544  0.58776
gpty_lag1       0.23095    0.19723   1.171  0.24526
d_2020Q2      -31.45368    4.22813  -7.439 1.29e-10 ***
d_2021Q1      -16.29932    5.56245  -2.930  0.00447 **
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 3.823 on 76 degrees of freedom
Multiple R-squared:  0.6273,	Adjusted R-squared:  0.5341
F-statistic: 6.731 on 19 and 76 DF,  p-value: 6.777e-10

In [10]:
# p-stat (sum)
linearHypothesis(wage_model1, "gw_lag1 + gw_lag2 + gw_lag3 + gw_lag4 = 0")
# p-stat (joint)
linearHypothesis(wage_model1, c("gw_lag1=0", "gw_lag2=0", "gw_lag3=0", "gw_lag4=0"))

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 77     1153.963 NA       NA        NA         NA
2 76     1110.879  1 43.08377  2.947546 0.09008118

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 80     1337.597 NA       NA        NA          NA
2 76     1110.879  4 226.7177  3.877682 0.006406237

In [11]:
# p-stat (sum)
linearHypothesis(wage_model1, "cf1_lag1 + cf1_lag2 + cf1_lag3 + cf1_lag4 = 0")
# p-stat (joint)
linearHypothesis(wage_model1, c("cf1_lag1=0", "cf1_lag2=0", "cf1_lag3=0", "cf1_lag4=0"))

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 77     1133.800 NA       NA        NA        NA
2 76     1110.879  1 22.92154  1.568161 0.2143143

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 80     1284.574 NA       NA        NA         NA
2 76     1110.879  4 173.6949  2.970803 0.02457723

In [12]:
# p-stat (sum)
linearHypothesis(wage_model1, "diff_cpi_lag1 + diff_cpi_lag2 + diff_cpi_lag3 + diff_cpi_lag4 = 0")
# p-stat (joint)
linearHypothesis(wage_model1, c("diff_cpi_lag1=0", "diff_cpi_lag2=0", "diff_cpi_lag3=0", "diff_cpi_lag4=0"))

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 77     1159.512 NA       NA        NA         NA
2 76     1110.879  1 48.63263  3.327167 0.07207502

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 80     1304.174 NA       NA        NA         NA
2 76     1110.879  4 193.2954  3.306042 0.01493591

In [13]:
# p-stat (sum)
linearHypothesis(wage_model1, "vu_lag1 + vu_lag2 + vu_lag3 + vu_lag4 = 0")
# p-stat (joint)
linearHypothesis(wage_model1, c("vu_lag1=0", "vu_lag2=0", "vu_lag3=0", "vu_lag4=0"))

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 77     1218.384 NA       NA        NA          NA
2 76     1110.879  1 107.5051  7.354889 0.008266825

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 80     1397.684 NA       NA        NA          NA
2 76     1110.879  4 286.8054  4.905397 0.001426118

In [14]:
# vertical Phillips curve in LR
my_constraints <- 'gw_lag1 + gw_lag2 + gw_lag3 + gw_lag4 + cf1_lag1 + cf1_lag2 + cf1_lag3 + cf1_lag4 = 1'
wage_model_restricted1 <- restriktor(wage_model1, 
                                    constraints = my_constraints)

summary(wage_model_restricted1)

Call:
conLM.lm(object = object, constraints = constraints)

Restriktor: restricted linear model:

Residuals:
     Min       1Q   Median       3Q      Max
-8.78130 -2.15844 -0.04948  2.30845  8.99793

Coefficients:
                Estimate Std. Error t value  Pr(>|t|)
(Intercept)    -0.535023   0.699901 -0.7644  0.446980
gw_lag1        -0.197334   0.103212 -1.9119  0.059655 .
gw_lag2         0.131896   0.108391  1.2169  0.227427
gw_lag3         0.318198   0.113300  2.8085  0.006324 **
gw_lag4         0.082480   0.098393  0.8383  0.404507
cf1_lag1        1.805644   1.405504  1.2847  0.202801
cf1_lag2        2.538850   2.351821  1.0795  0.283768
cf1_lag3       -0.375885   2.321328 -0.1619  0.871793
cf1_lag4       -3.303850   1.743233 -1.8952  0.061863 .
diff_cpi_lag1  -0.992372   0.646770 -1.5344  0.129096
diff_cpi_lag2  -1.343808   0.721022 -1.8638  0.066219 .
diff_cpi_lag3   0.641716   0.718406  0.8932  0.374544
diff_cpi_lag4   0.270683   0.516380  0.5242  0.601669
vu_lag1        -2.723566   5.586851 -0.4875  0.627310
vu_lag2        -6.423127   8.691545 -0.7390  0.462178
vu_lag3        13.153708  10.237528  1.2849  0.202746
vu_lag4        -1.082226   6.766246 -0.1599  0.873349
gpty_lag1       0.245363   0.206712  1.1870  0.238932
d_2020Q2      -28.278414   4.285696 -6.5983 4.965e-09 ***
d_2021Q1      -11.702216   5.596466 -2.0910  0.039870 *
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 4.0083 on 76 degrees of freedom
Standard errors: standard
Multiple R-squared reduced from 0.627 to 0.612

Generalized order-restricted information criterion:
 Loglik Penalty   goric
-258.92   20.00  557.83

In [15]:
beta <- coef(wage_model_restricted1)
sum_gw <- sum(beta[grep("gw_lag", names(beta))])
sum_gw
sum_cf1 <- sum(beta[grep("cf1_lag", names(beta))])
sum_cf1 
sum_vu <- sum(beta[grep("vu_lag", names(beta))])
sum_vu
sum_catchup <- sum(beta[grep("diff_cpi_lag", names(beta))])
sum_catchup
sum_gpty <- sum(beta[grep("gpty_lag1", names(beta))])
sum_gpty

[1] 0.3352403

[1] 0.6647598

[1] 2.92479

[1] -1.423781

[1] 0.2453635

## Compensation per hour

In [25]:
lag_model <- df2 %>%
  mutate(

    d_2020Q2 = ifelse(date == "2020Q2", 1, 0),
    d_2021Q1 = ifelse(date == "2021Q1", 1, 0),
    
    gw_lag1 = lag(gw, 1),
    gw_lag2 = lag(gw, 2),
    gw_lag3 = lag(gw, 3),
    gw_lag4 = lag(gw, 4),

    cf1_lag1 = lag(cf1, 1),
    cf1_lag2 = lag(cf1, 2),
    cf1_lag3 = lag(cf1, 3),
    cf1_lag4 = lag(cf1, 4),

    diff_cpi_lag1 = lag(diff_cpi, 1),
    diff_cpi_lag2 = lag(diff_cpi, 2),
    diff_cpi_lag3 = lag(diff_cpi, 3),
    diff_cpi_lag4 = lag(diff_cpi, 4),

    vu_lag1 = lag(vu, 1),
    vu_lag2 = lag(vu, 2),
    vu_lag3 = lag(vu, 3),
    vu_lag4 = lag(vu, 4),

    gpty_lag1 = lag(gpty, 1)
  ) %>%

  select(
    date, 
    gw,          
    gw_lag1, gw_lag2, gw_lag3, gw_lag4,
    cf1_lag1, cf1_lag2, cf1_lag3, cf1_lag4,
    diff_cpi_lag1, diff_cpi_lag2, diff_cpi_lag3, diff_cpi_lag4,
    vu_lag1, vu_lag2, vu_lag3, vu_lag4,
    gpty_lag1,
    d_2020Q2, d_2021Q1,
  ) %>%

  na.omit()

wage_model2 <- lm(gw ~ gw_lag1 + gw_lag2 + gw_lag3 + gw_lag4 + 
                      cf1_lag1 + cf1_lag2 + cf1_lag3 + cf1_lag4 +
                      diff_cpi_lag1 + diff_cpi_lag2 + diff_cpi_lag3 + diff_cpi_lag4 +
                      vu_lag1 + vu_lag2 + vu_lag3 + vu_lag4 +
                      gpty_lag1 +
                      d_2020Q2 + d_2021Q1,
                      data = lag_model)

summary(wage_model2)

Call:
lm(formula = gw ~ gw_lag1 + gw_lag2 + gw_lag3 + gw_lag4 + cf1_lag1 +
    cf1_lag2 + cf1_lag3 + cf1_lag4 + diff_cpi_lag1 + diff_cpi_lag2 +
    diff_cpi_lag3 + diff_cpi_lag4 + vu_lag1 + vu_lag2 + vu_lag3 +
    vu_lag4 + gpty_lag1 + d_2020Q2 + d_2021Q1, data = lag_model)

Residuals:
     Min       1Q   Median       3Q      Max
-13.0270  -2.8078   0.4523   3.6646  15.1345

Coefficients:
               Estimate Std. Error t value Pr(>|t|)
(Intercept)     1.31670    2.40037   0.549 0.584930
gw_lag1        -0.50595    0.12447  -4.065 0.000116 ***
gw_lag2        -0.03492    0.12352  -0.283 0.778156
gw_lag3         0.31678    0.11639   2.722 0.008050 **
gw_lag4         0.26984    0.10738   2.513 0.014095 *
cf1_lag1        0.02728    2.22601   0.012 0.990253
cf1_lag2        4.75327    3.56735   1.332 0.186698
cf1_lag3       -1.41415    3.59022  -0.394 0.694764
cf1_lag4       -3.05598    2.64658  -1.155 0.251835
diff_cpi_lag1  -0.80562    0.99487  -0.810 0.420598
diff_cpi_lag2  -1.24624    1.10147  -1.131 0.261430
diff_cpi_lag3   0.57970    1.10684   0.524 0.601982
diff_cpi_lag4   0.16495    0.80675   0.204 0.838541
vu_lag1         6.70649    7.73703   0.867 0.388778
vu_lag2       -23.98826   12.58338  -1.906 0.060386 .
vu_lag3        40.36069   15.20638   2.654 0.009678 **
vu_lag4       -19.45658   10.34272  -1.881 0.063777 .
gpty_lag1       0.18017    0.47676   0.378 0.706563
d_2020Q2        0.78647    7.51845   0.105 0.916964
d_2021Q1      -12.21158    8.62690  -1.416 0.161000
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 6.115 on 76 degrees of freedom
Multiple R-squared:  0.4735,	Adjusted R-squared:  0.3419
F-statistic: 3.598 on 19 and 76 DF,  p-value: 3.53e-05

In [26]:
# p-stat (sum)
linearHypothesis(wage_model2, "gw_lag1 + gw_lag2 + gw_lag3 + gw_lag4 = 0")
# p-stat (joint)
linearHypothesis(wage_model2, c("gw_lag1=0", "gw_lag2=0", "gw_lag3=0", "gw_lag4=0"))

  Res.Df RSS      Df Sum of Sq F          Pr(>F)
1 77     2842.706 NA        NA         NA        NA
2 76     2841.938  1 0.7679998 0.02053809 0.8864237

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 80     3922.048 NA      NA         NA           NA
2 76     2841.938  4 1080.11   7.221161 5.536526e-05

In [27]:
# p-stat (sum)
linearHypothesis(wage_model2, "cf1_lag1 + cf1_lag2 + cf1_lag3 + cf1_lag4 = 0")
# p-stat (joint)
linearHypothesis(wage_model2, c("cf1_lag1=0", "cf1_lag2=0", "cf1_lag3=0", "cf1_lag4=0"))

  Res.Df RSS      Df Sum of Sq F         Pr(>F)
1 77     2849.078 NA       NA         NA        NA
2 76     2841.938  1 7.140396  0.1909507 0.6633656

  Res.Df RSS      Df Sum of Sq F       Pr(>F)
1 80     3014.807 NA       NA       NA        NA
2 76     2841.938  4 172.8692  1.15573 0.3371104

In [28]:
# p-stat (sum)
linearHypothesis(wage_model2, "diff_cpi_lag1 + diff_cpi_lag2 + diff_cpi_lag3 + diff_cpi_lag4 = 0")
# p-stat (joint)
linearHypothesis(wage_model2, c("diff_cpi_lag1=0", "diff_cpi_lag2=0", "diff_cpi_lag3=0", "diff_cpi_lag4=0"))

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 77     2993.574 NA       NA        NA         NA
2 76     2841.938  1 151.6358  4.055093 0.04757832

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 80     3043.069 NA       NA        NA        NA
2 76     2841.938  4 201.1309  1.344677 0.2612233

In [29]:
# p-stat (sum)
linearHypothesis(wage_model2, "vu_lag1 + vu_lag2 + vu_lag3 + vu_lag4 = 0")
# p-stat (joint)
linearHypothesis(wage_model2, c("vu_lag1=0", "vu_lag2=0", "vu_lag3=0", "vu_lag4=0"))

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 77     2970.024 NA       NA        NA         NA
2 76     2841.938  1 128.0866  3.425332 0.06808906

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 80     3305.252 NA       NA        NA         NA
2 76     2841.938  4 463.3139  3.097522 0.02035895

In [30]:
# vertical Phillips curve in LR
my_constraints <- 'gw_lag1 + gw_lag2 + gw_lag3 + gw_lag4 + cf1_lag1 + cf1_lag2 + cf1_lag3 + cf1_lag4 = 1'
wage_model_restricted2 <- restriktor(wage_model2, 
                                    constraints = my_constraints)

summary(wage_model_restricted2)

Call:
conLM.lm(object = object, constraints = constraints)

Restriktor: restricted linear model:

Residuals:
      Min        1Q    Median        3Q       Max
-12.17550  -3.12994   0.47221   3.65167  15.91184

Coefficients:
                Estimate Std. Error t value  Pr(>|t|)
(Intercept)    -0.612544   1.405237 -0.4359 0.6641441
gw_lag1        -0.507395   0.124443 -4.0773 0.0001111 ***
gw_lag2        -0.020617   0.122662 -0.1681 0.8669643
gw_lag3         0.323406   0.116189  2.7834 0.0067827 **
gw_lag4         0.264876   0.107256  2.4696 0.0157709 *
cf1_lag1        0.615703   2.145188  0.2870 0.7748812
cf1_lag2        4.669488   3.565958  1.3095 0.1943227
cf1_lag3       -1.521847   3.588174 -0.4241 0.6726702
cf1_lag4       -2.823614   2.635890 -1.0712 0.2874613
diff_cpi_lag1  -1.003310   0.974570 -1.0295 0.3065149
diff_cpi_lag2  -1.233256   1.101266 -1.1199 0.2663029
diff_cpi_lag3   0.691493   1.100958  0.6281 0.5318323
diff_cpi_lag4  -0.076298   0.769094 -0.0992 0.9212366
vu_lag1         8.614733   7.492965  1.1497 0.2538686
vu_lag2       -25.517160  12.487140 -2.0435 0.0444714 *
vu_lag3        42.145122  15.097807  2.7915 0.0066322 **
vu_lag4       -21.884092  10.047594 -2.1780 0.0325047 *
gpty_lag1       0.170065   0.476601  0.3568 0.7222081
d_2020Q2        2.492593   7.318048  0.3406 0.7343377
d_2021Q1       -9.955020   8.320300 -1.1965 0.2352310
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 6.1144 on 76 degrees of freedom
Standard errors: standard
Multiple R-squared remains 0.474

Generalized order-restricted information criterion:
 Loglik Penalty   goric
-299.45   20.00  638.91

In [31]:
beta <- coef(wage_model_restricted2)
sum_gw <- sum(beta[grep("gw_lag", names(beta))])
sum_gw
sum_cf1 <- sum(beta[grep("cf1_lag", names(beta))])
sum_cf1 
sum_vu <- sum(beta[grep("vu_lag", names(beta))])
sum_vu
sum_catchup <- sum(beta[grep("diff_cpi_lag", names(beta))])
sum_catchup
sum_gpty <- sum(beta[grep("gpty_lag1", names(beta))])
sum_gpty

[1] 0.06026945

[1] 0.9397305

[1] 3.358603

[1] -1.621371

[1] 0.1700654