gw
cf1
diff_hicp
vu
gpty

In [2]:
library(dplyr)
library(readr)
library(restriktor)
library(car)

In [5]:
setwd("/Users/smirovaclav/Documents/blanchard_papery/czechia_data/master_thesis/")

In [6]:
df1 <- read_csv("data_processing/final_dataset/intermediate_data_per_employee_cze.csv", show_col_types = FALSE)
df2 <- read_csv("data_processing/final_dataset/intermediate_data_per_hour_cze.csv", show_col_types = FALSE)

In [7]:
lag_model <- df1 %>%
  mutate(
      
    d_2020Q2 = ifelse(date == "2020Q2", 1, 0),
    d_2021Q1 = ifelse(date == "2021Q1", 1, 0),
    
    gw_lag1 = lag(gw, 1),
    gw_lag2 = lag(gw, 2),
    gw_lag3 = lag(gw, 3),
    gw_lag4 = lag(gw, 4),

    cf1_lag1 = lag(cf1, 1),
    cf1_lag2 = lag(cf1, 2),
    cf1_lag3 = lag(cf1, 3),
    cf1_lag4 = lag(cf1, 4),

    diff_hicp_lag1 = lag(diff_hicp, 1),
    diff_hicp_lag2 = lag(diff_hicp, 2),
    diff_hicp_lag3 = lag(diff_hicp, 3),
    diff_hicp_lag4 = lag(diff_hicp, 4),

    vu_lag1 = lag(vu, 1),
    vu_lag2 = lag(vu, 2),
    vu_lag3 = lag(vu, 3),
    vu_lag4 = lag(vu, 4),

    gpty_lag1 = lag(gpty, 1)
  ) %>%

  select(
    date, 
    gw,          
    gw_lag1, gw_lag2, gw_lag3, gw_lag4,
    cf1_lag1, cf1_lag2, cf1_lag3, cf1_lag4,
    diff_hicp_lag1, diff_hicp_lag2, diff_hicp_lag3, diff_hicp_lag4,
    vu_lag1, vu_lag2, vu_lag3, vu_lag4,
    gpty_lag1,
    d_2020Q2, d_2021Q1
  ) %>%

  na.omit()

wage_model1 <- lm(gw ~ gw_lag1 + gw_lag2 + gw_lag3 + gw_lag4 + 
                      cf1_lag1 + cf1_lag2 + cf1_lag3 + cf1_lag4 +
                      diff_hicp_lag1 + diff_hicp_lag2 + diff_hicp_lag3 + diff_hicp_lag4 +
                      vu_lag1 + vu_lag2 + vu_lag3 + vu_lag4 +
                      gpty_lag1 +
                      d_2020Q2 + d_2021Q1,
                      data = lag_model)

summary(wage_model1)

Call:
lm(formula = gw ~ gw_lag1 + gw_lag2 + gw_lag3 + gw_lag4 + cf1_lag1 +
    cf1_lag2 + cf1_lag3 + cf1_lag4 + diff_hicp_lag1 + diff_hicp_lag2 +
    diff_hicp_lag3 + diff_hicp_lag4 + vu_lag1 + vu_lag2 + vu_lag3 +
    vu_lag4 + gpty_lag1 + d_2020Q2 + d_2021Q1, data = lag_model)

Residuals:
    Min      1Q  Median      3Q     Max
-9.3134 -1.8892  0.0054  2.1491  7.4420

Coefficients:
                Estimate Std. Error t value Pr(>|t|)
(Intercept)      3.08524    1.47868   2.086  0.04029 *
gw_lag1         -0.15610    0.10261  -1.521  0.13235
gw_lag2          0.17953    0.10993   1.633  0.10658
gw_lag3          0.32854    0.11130   2.952  0.00420 **
gw_lag4          0.09470    0.09662   0.980  0.33012
cf1_lag1         0.29451    1.38605   0.212  0.83230
cf1_lag2         2.28667    2.28302   1.002  0.31971
cf1_lag3         0.18411    2.23524   0.082  0.93457
cf1_lag4        -3.41258    1.71723  -1.987  0.05050 .
diff_hicp_lag1  -0.40783    0.62264  -0.655  0.51444
diff_hicp_lag2  -1.19824    0.69448  -1.725  0.08852 .
diff_hicp_lag3   0.29033    0.69498   0.418  0.67730
diff_hicp_lag4   0.77811    0.54312   1.433  0.15605
vu_lag1         -7.84057    5.92963  -1.322  0.19004
vu_lag2         -2.19221    8.66977  -0.253  0.80106
vu_lag3          8.52556   10.10281   0.844  0.40138
vu_lag4          4.38104    6.91339   0.634  0.52818
gpty_lag1        0.24338    0.20176   1.206  0.23144
d_2020Q2       -31.06939    4.32891  -7.177 4.06e-10 ***
d_2021Q1       -16.12912    5.76083  -2.800  0.00648 **
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 3.916 on 76 degrees of freedom
Multiple R-squared:  0.6089,	Adjusted R-squared:  0.5111
F-statistic: 6.227 on 19 and 76 DF,  p-value: 3.314e-09

In [8]:
# p-stat (sum)
linearHypothesis(wage_model1, "gw_lag1 + gw_lag2 + gw_lag3 + gw_lag4 = 0")
# p-stat (joint)
linearHypothesis(wage_model1, c("gw_lag1=0", "gw_lag2=0", "gw_lag3=0", "gw_lag4=0"))

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 77     1207.464 NA      NA         NA        NA
2 76     1165.642  1 41.8222   2.726812 0.1028025

  Res.Df RSS      Df Sum of Sq F       Pr(>F)
1 80     1390.030 NA       NA       NA        NA
2 76     1165.642  4 224.3885  3.65754 0.0088695

In [9]:
# p-stat (sum)
linearHypothesis(wage_model1, "cf1_lag1 + cf1_lag2 + cf1_lag3 + cf1_lag4 = 0")
# p-stat (joint)
linearHypothesis(wage_model1, c("cf1_lag1=0", "cf1_lag2=0", "cf1_lag3=0", "cf1_lag4=0"))

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 77     1186.697 NA       NA        NA        NA
2 76     1165.642  1 21.05506  1.372792 0.2449928

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 80     1286.917 NA       NA        NA        NA
2 76     1165.642  4 121.2751  1.976788 0.1065407

In [10]:
# p-stat (sum)
linearHypothesis(wage_model1, "diff_hicp_lag1 + diff_hicp_lag2 + diff_hicp_lag3 + diff_hicp_lag4= 0")
# p-stat (joint)
linearHypothesis(wage_model1, c("diff_hicp_lag1=0", "diff_hicp_lag2=0", "diff_hicp_lag3=0",  "diff_hicp_lag4=0"))

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 77     1191.153 NA       NA        NA        NA
2 76     1165.642  1 25.51114  1.663329 0.2010653

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 80     1304.174 NA       NA        NA         NA
2 76     1165.642  4 138.5324  2.258083 0.07060666

In [11]:
# p-stat (sum)
linearHypothesis(wage_model1, "vu_lag1 + vu_lag2 + vu_lag3 + vu_lag4 = 0")
# p-stat (joint)
linearHypothesis(wage_model1, c("vu_lag1=0", "vu_lag2=0", "vu_lag3=0", "vu_lag4=0"))

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 77     1253.023 NA       NA        NA         NA
2 76     1165.642  1 87.38101  5.697253 0.01947883

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 80     1422.950 NA       NA        NA          NA
2 76     1165.642  4 257.3076  4.194122 0.004020947

In [12]:
# vertical Phillips curve in LR
my_constraints <- 'gw_lag1 + gw_lag2 + gw_lag3 + gw_lag4 + cf1_lag1 + cf1_lag2 + cf1_lag3 + cf1_lag4 = 1'
wage_model_restricted1 <- restriktor(wage_model1, 
                                    constraints = my_constraints)

summary(wage_model_restricted1)

Call:
conLM.lm(object = object, constraints = constraints)

Restriktor: restricted linear model:

Residuals:
     Min       1Q   Median       3Q      Max
-9.47559 -2.27295 -0.07289  2.29752  9.29698

Coefficients:
                 Estimate Std. Error t value  Pr(>|t|)
(Intercept)     -0.538909   0.717235 -0.7514  0.454750
gw_lag1         -0.201485   0.105589 -1.9082  0.060141 .
gw_lag2          0.116199   0.112085  1.0367  0.303164
gw_lag3          0.313842   0.115887  2.7082  0.008354 **
gw_lag4          0.077546   0.100505  0.7716  0.442763
cf1_lag1         1.212841   1.402847  0.8646  0.390003
cf1_lag2         2.264810   2.379793  0.9517  0.344274
cf1_lag3         0.015997   2.329142  0.0069  0.994538
cf1_lag4        -2.799750   1.775100 -1.5772  0.118895
diff_hicp_lag1  -0.756719   0.635613 -1.1905  0.237542
diff_hicp_lag2  -1.131642   0.723485 -1.5642  0.121936
diff_hicp_lag3   0.456632   0.721729  0.6327  0.528833
diff_hicp_lag4   0.237478   0.528294  0.4495  0.654337
vu_lag1         -2.206505   5.805724 -0.3801  0.704963
vu_lag2         -6.323578   8.902494 -0.7103  0.479683
vu_lag3         11.738575  10.461424  1.1221  0.265360
vu_lag4         -0.444476   6.973766 -0.0637  0.949348
gpty_lag1        0.259127   0.210230  1.2326  0.221528
d_2020Q2       -28.038611   4.365808 -6.4223 1.053e-08 ***
d_2021Q1       -11.266999   5.719305 -1.9700  0.052482 .
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 4.0823 on 76 degrees of freedom
Standard errors: standard
Multiple R-squared reduced from 0.609 to 0.596

Generalized order-restricted information criterion:
 Loglik Penalty   goric
-260.67   20.00  561.34

In [13]:
beta <- coef(wage_model_restricted1)
sum_gw <- sum(beta[grep("gw_lag", names(beta))])
sum_gw
sum_cf1 <- sum(beta[grep("cf1_lag", names(beta))])
sum_cf1 
sum_vu <- sum(beta[grep("vu_lag", names(beta))])
sum_vu
sum_catchup <- sum(beta[grep("diff_hicp_lag", names(beta))])
sum_catchup
sum_gpty <- sum(beta[grep("gpty_lag1", names(beta))])
sum_gpty

[1] 0.3061025

[1] 0.6938975

[1] 2.764016

[1] -1.19425

[1] 0.2591274

In [14]:
lag_model <- df2 %>%
  mutate(

    d_2020Q2 = ifelse(date == "2020Q2", 1, 0),
    d_2021Q1 = ifelse(date == "2021Q1", 1, 0),
    
    gw_lag1 = lag(gw, 1),
    gw_lag2 = lag(gw, 2),
    gw_lag3 = lag(gw, 3),
    gw_lag4 = lag(gw, 4),

    cf1_lag1 = lag(cf1, 1),
    cf1_lag2 = lag(cf1, 2),
    cf1_lag3 = lag(cf1, 3),
    cf1_lag4 = lag(cf1, 4),

    diff_hicp_lag1 = lag(diff_hicp, 1),
    diff_hicp_lag2 = lag(diff_hicp, 2),
    diff_hicp_lag3 = lag(diff_hicp, 3),
    diff_hicp_lag4 = lag(diff_hicp, 4),

    vu_lag1 = lag(vu, 1),
    vu_lag2 = lag(vu, 2),
    vu_lag3 = lag(vu, 3),
    vu_lag4 = lag(vu, 4),

    gpty_lag1 = lag(gpty, 1)
  ) %>%

  select(
    date, 
    gw,          
    gw_lag1, gw_lag2, gw_lag3, gw_lag4,
    cf1_lag1, cf1_lag2, cf1_lag3, cf1_lag4,
    diff_hicp_lag1, diff_hicp_lag2, diff_hicp_lag3, diff_hicp_lag4,
    vu_lag1, vu_lag2, vu_lag3, vu_lag4,
    gpty_lag1,
    d_2020Q2, d_2021Q1
  ) %>%

  na.omit()

wage_model2 <- lm(gw ~ gw_lag1 + gw_lag2 + gw_lag3 + gw_lag4 + 
                      cf1_lag1 + cf1_lag2 + cf1_lag3 + cf1_lag4 +
                      diff_hicp_lag1 + diff_hicp_lag2 + diff_hicp_lag3 + diff_hicp_lag4 +
                      vu_lag1 + vu_lag2 + vu_lag3 + vu_lag4 +
                      gpty_lag1 +
                      d_2020Q2 + d_2021Q1,
                      data = lag_model)

summary(wage_model2)

Call:
lm(formula = gw ~ gw_lag1 + gw_lag2 + gw_lag3 + gw_lag4 + cf1_lag1 +
    cf1_lag2 + cf1_lag3 + cf1_lag4 + diff_hicp_lag1 + diff_hicp_lag2 +
    diff_hicp_lag3 + diff_hicp_lag4 + vu_lag1 + vu_lag2 + vu_lag3 +
    vu_lag4 + gpty_lag1 + d_2020Q2 + d_2021Q1, data = lag_model)

Residuals:
     Min       1Q   Median       3Q      Max
-13.1499  -2.9264   0.4681   3.5468  15.3818

Coefficients:
                Estimate Std. Error t value Pr(>|t|)
(Intercept)      1.18267    2.47579   0.478 0.634240
gw_lag1         -0.51398    0.12618  -4.073 0.000113 ***
gw_lag2         -0.03643    0.12540  -0.291 0.772222
gw_lag3          0.32381    0.11745   2.757 0.007301 **
gw_lag4          0.27227    0.10811   2.518 0.013892 *
cf1_lag1        -0.90822    2.18670  -0.415 0.679066
cf1_lag2         4.34702    3.56261   1.220 0.226170
cf1_lag3        -0.44318    3.54954  -0.125 0.900967
cf1_lag4        -2.62968    2.67108  -0.985 0.327994
diff_hicp_lag1  -0.29274    0.96978  -0.302 0.763577
diff_hicp_lag2  -1.08237    1.08925  -0.994 0.323529
diff_hicp_lag3   0.08117    1.09900   0.074 0.941319
diff_hicp_lag4   0.26113    0.81804   0.319 0.750437
vu_lag1          7.38640    7.92249   0.932 0.354117
vu_lag2        -24.11001   12.73444  -1.893 0.062126 .
vu_lag3         39.40012   15.33533   2.569 0.012151 *
vu_lag4        -19.31228   10.46244  -1.846 0.068806 .
gpty_lag1        0.17476    0.48251   0.362 0.718221
d_2020Q2         1.07344    7.59448   0.141 0.887972
d_2021Q1       -11.50151    8.74200  -1.316 0.192243
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 6.161 on 76 degrees of freedom
Multiple R-squared:  0.4657,	Adjusted R-squared:  0.3321
F-statistic: 3.486 on 19 and 76 DF,  p-value: 5.431e-05

In [15]:
# p-stat (sum)
linearHypothesis(wage_model2, "gw_lag1 + gw_lag2 + gw_lag3 + gw_lag4 = 0")
# p-stat (joint)
linearHypothesis(wage_model2, c("gw_lag1=0", "gw_lag2=0", "gw_lag3=0", "gw_lag4=0"))

  Res.Df RSS      Df Sum of Sq F          Pr(>F)
1 77     2885.173 NA        NA         NA        NA
2 76     2884.424  1 0.7488341 0.01973059 0.8886637

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 80     4004.222 NA       NA        NA           NA
2 76     2884.424  4 1119.798  7.376223 4.487666e-05

In [16]:
# p-stat (sum)
linearHypothesis(wage_model2, "cf1_lag1 + cf1_lag2 + cf1_lag3 + cf1_lag4 = 0")
# p-stat (joint)
linearHypothesis(wage_model2, c("cf1_lag1=0", "cf1_lag2=0", "cf1_lag3=0", "cf1_lag4=0"))

  Res.Df RSS      Df Sum of Sq F         Pr(>F)
1 77     2893.811 NA       NA         NA        NA
2 76     2884.424  1 9.386443  0.2473179 0.6204058

  Res.Df RSS      Df Sum of Sq F         Pr(>F)
1 80     2996.095 NA       NA         NA        NA
2 76     2884.424  4 111.6706  0.7355854 0.5705502

In [17]:
# p-stat (sum)
linearHypothesis(wage_model2, "diff_hicp_lag1 + diff_hicp_lag2 + diff_hicp_lag3 + diff_hicp_lag4= 0")
# p-stat (joint)
linearHypothesis(wage_model2, c("diff_hicp_lag1=0", "diff_hicp_lag2=0", "diff_hicp_lag3=0",  "diff_hicp_lag4=0"))

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 77     2991.273 NA      NA         NA         NA
2 76     2884.424  1 106.849   2.815303 0.09747735

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 80     3043.069 NA       NA        NA        NA
2 76     2884.424  4 158.6444  1.045007 0.3897361

In [18]:
# p-stat (sum)
linearHypothesis(wage_model2, "vu_lag1 + vu_lag2 + vu_lag3 + vu_lag4 = 0")
# p-stat (joint)
linearHypothesis(wage_model2, c("vu_lag1=0", "vu_lag2=0", "vu_lag3=0", "vu_lag4=0"))

  Res.Df RSS      Df Sum of Sq F       Pr(>F)
1 77     2996.829 NA       NA       NA        NA
2 76     2884.424  1 112.4045  2.96168 0.0893282

  Res.Df RSS      Df Sum of Sq F        Pr(>F)
1 80     3311.320 NA       NA        NA         NA
2 76     2884.424  4 426.8954  2.812004 0.03111578

In [19]:
# vertical Phillips curve in LR
my_constraints <- 'gw_lag1 + gw_lag2 + gw_lag3 + gw_lag4 + cf1_lag1 + cf1_lag2 + cf1_lag3 + cf1_lag4 = 1'
wage_model_restricted2 <- restriktor(wage_model2, 
                                    constraints = my_constraints)

summary(wage_model_restricted2)

Call:
conLM.lm(object = object, constraints = constraints)

Restriktor: restricted linear model:

Residuals:
     Min       1Q   Median       3Q      Max
-13.3225  -3.1144   0.4432   3.6299  16.0499

Coefficients:
                 Estimate Std. Error t value  Pr(>|t|)
(Intercept)     -0.596002   1.415245 -0.4211  0.674849
gw_lag1         -0.517342   0.125928 -4.1082 9.964e-05 ***
gw_lag2         -0.024378   0.124456 -0.1959  0.845230
gw_lag3          0.330012   0.117061  2.8192  0.006136 **
gw_lag4          0.267288   0.107800  2.4795  0.015372 *
cf1_lag1        -0.442550   2.117938 -0.2090  0.835044
cf1_lag2         4.313302   3.557028  1.2126  0.229033
cf1_lag3        -0.506335   3.543450 -0.1429  0.886753
cf1_lag4        -2.419997   2.656326 -0.9110  0.365159
diff_hicp_lag1  -0.460565   0.949241 -0.4852  0.628936
diff_hicp_lag2  -1.087912   1.087590 -1.0003  0.320342
diff_hicp_lag3   0.184749   1.090977  0.1693  0.865977
diff_hicp_lag4   0.040581   0.777180  0.0522  0.958494
vu_lag1          9.212205   7.632022  1.2070  0.231158
vu_lag2        -25.547851  12.609218 -2.0261  0.046262 *
vu_lag3         40.990820  15.204520  2.6960  0.008638 **
vu_lag4        -21.499019  10.145108 -2.1192  0.037344 *
gpty_lag1        0.156688   0.481338  0.3255  0.745678
d_2020Q2         2.652920   7.366322  0.3601  0.719740
d_2021Q1        -9.323908   8.368660 -1.1141  0.268728
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 6.1513 on 76 degrees of freedom
Standard errors: standard
Multiple R-squared remains 0.466

Generalized order-restricted information criterion:
 Loglik Penalty   goric
-300.03   20.00  640.06

In [20]:
beta <- coef(wage_model_restricted2)
sum_gw <- sum(beta[grep("gw_lag", names(beta))])
sum_gw
sum_cf1 <- sum(beta[grep("cf1_lag", names(beta))])
sum_cf1 
sum_vu <- sum(beta[grep("vu_lag", names(beta))])
sum_vu
sum_catchup <- sum(beta[grep("diff_hicp_lag", names(beta))])
sum_catchup
sum_gpty <- sum(beta[grep("gpty_lag1", names(beta))])
sum_gpty

[1] 0.05558092

[1] 0.9444191

[1] 3.156155

[1] -1.323146

[1] 0.1566877